apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-auth-secret-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-auth-secret
  data:
  - secretKey: GF_AUTH_AZUREAD_CLIENT_ID
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: azure_client_id
  - secretKey: GF_AUTH_AZUREAD_CLIENT_SECRET
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: azure_client_secret
  - secretKey: GF_DATABASE_PASSWORD
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: db_password
  - secretKey: GF_DATABASE_USER
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: db_user