{{ if .Values.grafanaBackup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafana-backup-tool
spec:
  schedule: {{ .Values.grafanaBackup.schedule }}
  failedJobsHistoryLimit: {{ .Values.grafanaBackup.failedJobsHistoryLimit | default 3 }}
  successfulJobsHistoryLimit: {{ .Values.grafanaBackup.successfulJobsHistoryLimit | default 3 }}
  jobTemplate:
    metadata:
      labels:
        app: grafana-backup-tool
    spec:
      activeDeadlineSeconds: 3600
      template:
        metadata:
          annotations:
            linkerd.io/inject: disabled
        spec:
          restartPolicy: "Never"
          containers:
            - name: grafana-backup-tool
              image: {{ .Values.grafanaBackup.image.repository }}:{{ .Values.grafanaBackup.image.tag }}
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: grafana-backup-secret
              resources:
                {{- toYaml .Values.grafanaBackup.resources | nindent 16 }}
{{ end }}