{{ if .Values.grafanaBackup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafana-backup-tool
spec:
  schedule: {{ .Values.grafanaBackup.schedule }}
  jobTemplate:
    metadata:
      labels:
        app: grafana-backup-tool
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: grafana-backup-tool
              image: {{ .Values.grafanaBackup.image.repository }}:{{ .Values.grafanaBackup.image.tag }}
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: grafana-backup-secret
{{ end }}