apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: grafana-db-secret-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-db-secret
  data:
  - secretKey: mysql-root-password
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: db_root_password
  - secretKey: mysql-replication-password
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: db_replication_password
  - secretKey: mysql-password
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: db_password