apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-backup-secret-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-backup-secret
    template:
      type: kubernetes.io/secret
      engineVersion: v2
      data:
        GRAFANA_URL: "https://grafana.mattgerega.net"
        GRAFANA_TOKEN: "{{ .GRAFANA_BACKUP_TOKEN }}"
        GRAFANA_ADMIN_ACCOUNT: "{{ .GRAFANA_ADMIN_USER }}"
        GRAFANA_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        AWS_ENDPOINT_URL: "https://s3.mattgerega.net"
        AWS_S3_BUCKET_NAME: "grafana-backups"
        AWS_S3_BUCKET_KEY: "daily"
        AWS_DEFAULT_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_KEY }}"

  data:
    - secretKey: GRAFANA_BACKUP_TOKEN
      remoteRef:
        key: secrets-k8/monitoring/grafana
        property: backup_token
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: secrets-k8/monitoring/grafana
        property: admin_user
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: secrets-k8/monitoring/grafana
        property: admin_password
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: secrets-k8/monitoring/grafana
        property: s3_access_key
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: secrets-k8/monitoring/grafana
        property: s3_secret_key
