apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
  data:
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: secrets-k8/monitoring/grafana
        property: admin_user
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: secrets-k8/monitoring/grafana
        property: admin_password
