apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: grafana-auth-secret-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-auth-secret
    template:
      engineVersion: v2
      data:
        GF_AUTH_AZUREAD_CLIENT_ID: '{{ .client_id }}'
        GF_AUTH_AZUREAD_CLIENT_SECRET: '{{ .client_secret }}'
  data:
  - secretKey: client_id
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: azure_client_id
  - secretKey: client_secret
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: azure_client_secret