apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-runtime-overrides
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  overrides.yaml: |
    # Per-tenant overrides for Tempo
    # Retention is controlled by block_retention in hours

    overrides:
      internal:
        metrics_generator:
          processors: []
        ingestion:
          rate_limit_bytes: 5000000      # 5MB/s sustained rate
          burst_size_bytes: 10000000     # 10MB burst
        compaction:
          block_retention: 720h  # 30 days

      production:
        metrics_generator:
          processors: []
        ingestion:
          rate_limit_bytes: 10000000     # 10MB/s sustained rate
          burst_size_bytes: 20000000     # 20MB burst
        compaction:
          block_retention: 2160h  # 90 days

      nonproduction:
        metrics_generator:
          processors: []
        ingestion:
          rate_limit_bytes: 2000000      # 2MB/s sustained rate
          burst_size_bytes: 5000000      # 5MB burst
        compaction:
          block_retention: 168h  # 7 days
