apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cassandra
  labels:
    spydersoft.io/environment: internal
    spydersoft.io/category: application
spec:
  project: external-apps
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
    path: '/external/cassandra/'
    repoURL: https://bitbucket.org/spydersoftteam/ops-internal-cluster
    targetRevision: main
  destination:
    server: https://192.168.1.36:6443
    namespace: 'cassandra'
  syncPolicy:
    # automated: 
    #   prune: true 
    #   selfHeal: true
    syncOptions:   
    - CreateNamespace=true