apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tools
  labels:
    spydersoft.io/environment: internal
    spydersoft.io/category: app-set
spec:
  generators:
  - git:
      repoURL: https://bitbucket.org/spydersoftteam/ops-internal-cluster
      revision: HEAD
      directories:
      - path: external/tools/*
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        spydersoft.io/environment: internal
        spydersoft.io/category: 'tools'
    spec:
      project: external-apps
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
        path: '{{ path }}'
        repoURL: https://bitbucket.org/spydersoftteam/ops-internal-cluster
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: 'tools'
      ignoreDifferences:
      - group: '*'
        kind: 'MutatingWebhookConfiguration'
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
        - '.webhooks[]?.client'
      syncPolicy:
        # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        #   prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: false
        syncOptions:     # Sync options which modifies sync behavior
        - RespectIgnoreDifferences=true
