apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-autounseal-secret-es
  namespace: tools

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-autounseal-secret
    template:
      engineVersion: v2
      data:
        AZURE_TENANT_ID: "{{ `{{ .tenant_id }}` }}"
        AZURE_CLIENT_ID: "{{ `{{ .client_id }}` }}"
        AZURE_CLIENT_SECRET: "{{ `{{ .client_secret }}` }}"
        VAULT_AZUREKEYVAULT_VAULT_NAME: "{{ `{{ .vault_name }}` }}"
        VAULT_AZUREKEYVAULT_KEY_NAME: "{{ `{{ .key_name }}` }}"
  data:
    - secretKey: tenant_id
      remoteRef:
        key: secrets-k8/vault/autounseal
        property: tenant_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_id
      remoteRef:
        key: secrets-k8/vault/autounseal
        property: client_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        key: secrets-k8/vault/autounseal
        property: client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: vault_name
      remoteRef:
        key: secrets-k8/vault/autounseal
        property: vault_name
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: key_name
      remoteRef:
        key: secrets-k8/vault/autounseal
        property: key_name
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
