version: 5.0.1
description: Spoolman
appVersion: 0.16.1
name: spoolman
dependencies:
- version: 5.0.1
  name: common
  repository: https://bjw-s-labs.github.io/helm-charts
apiVersion: v2
type: application


