type: application
apiVersion: v2
dependencies:
- repository: https://bjw-s.github.io/helm-charts
  name: common
  version: 3.6.0
appVersion: 0.16.1
version: 3.6.0
description: Spoolman
name: spoolman


