version: 4.2.0
dependencies:
- repository: https://bjw-s-labs.github.io/helm-charts
  name: common
  version: 4.2.0
name: spoolman
appVersion: 0.16.1
apiVersion: v2
description: Spoolman
type: application


