appVersion: 0.16.1
apiVersion: v2
type: application
name: spoolman
description: Spoolman
version: 3.3.1
dependencies:
- repository: https://bjw-s.github.io/helm-charts
  name: common
  version: 3.3.1


