version: 3.5.0
type: application
name: spoolman
appVersion: 0.16.1
apiVersion: v2
dependencies:
- version: 3.5.0
  repository: https://bjw-s.github.io/helm-charts
  name: common
description: Spoolman


