dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 5.0.1
appVersion: 0.16.1
version: 5.0.1
name: spoolman
description: Spoolman
type: application
apiVersion: v2


