type: application
name: spoolman
apiVersion: v2
version: 5.0.1
description: Spoolman
dependencies:
- version: 5.0.1
  name: common
  repository: https://bjw-s-labs.github.io/helm-charts
appVersion: 0.16.1


