route:
  main:
    kind: HTTPRoute
    hostnames:
    - spoolman.mattgerega.net
    parentRefs:
    - name: main
      kind: Gateway
      group: gateway.networking.k8s.io
      namespace: envoy-gateway-system
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - kind: Service
        group: ""
        port: 8000
        name: spoolman
        weight: 1
    enabled: true
persistence:
  data:
    size: 2Gi
    globalMounts:
    - readOnly: false
      path: /home/app/.local/share/spoolman
    accessMode: ReadWriteMany
    storageClass: nfs-client
    enabled: true
    type: persistentVolumeClaim
controllers:
  main:
    containers:
      main:
        resources:
          requests:
            cpu: 5m
        env:
          TZ: America/New_York
        probes:
          startup:
            spec:
              periodSeconds: 5
              initialDelaySeconds: 0
              failureThreshold: 30
              timeoutSeconds: 1
            custom: false
            enabled: true
            type: TCP
          liveness:
            spec:
              periodSeconds: 10
              initialDelaySeconds: 0
              failureThreshold: 3
              timeoutSeconds: 1
            custom: false
            enabled: true
            type: TCP
          readiness:
            spec:
              periodSeconds: 10
              initialDelaySeconds: 0
              failureThreshold: 3
              timeoutSeconds: 1
            custom: false
            enabled: true
            type: TCP
        image:
          tag: 0.26.0
          pullPolicy: IfNotPresent
          repository: ghcr.io/donkie/spoolman
        strategy:
          type: Recreate
    replicas: 1
    revisionHistoryLimit: 3
    strategy: Recreate
    type: deployment
    enabled: true
service:
  main:
    ports:
      http:
        primary: true
        enabled: true
        port: 8000
    controller: main
    primary: true
    type: ClusterIP

