route:
  main:
    hostnames:
    - spoolman.mattgerega.net
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - name: spoolman
        group: ""
        weight: 1
        kind: Service
        port: 8000
    parentRefs:
    - name: main
      kind: Gateway
      group: gateway.networking.k8s.io
      namespace: envoy-gateway-system
    enabled: true
    kind: HTTPRoute
controllers:
  main:
    revisionHistoryLimit: 3
    replicas: 1
    type: deployment
    enabled: true
    strategy: Recreate
    containers:
      main:
        image:
          tag: 0.25.0
          repository: ghcr.io/donkie/spoolman
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 5m
        env:
          TZ: America/New_York
        probes:
          liveness:
            enabled: true
            custom: false
            type: TCP
            spec:
              periodSeconds: 10
              failureThreshold: 3
              initialDelaySeconds: 0
              timeoutSeconds: 1
          readiness:
            enabled: true
            custom: false
            type: TCP
            spec:
              periodSeconds: 10
              failureThreshold: 3
              initialDelaySeconds: 0
              timeoutSeconds: 1
          startup:
            enabled: true
            custom: false
            type: TCP
            spec:
              periodSeconds: 5
              failureThreshold: 30
              initialDelaySeconds: 0
              timeoutSeconds: 1
        strategy:
          type: Recreate
service:
  main:
    controller: main
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 8000
        primary: true
persistence:
  data:
    size: 2Gi
    accessMode: ReadWriteMany
    enabled: true
    type: persistentVolumeClaim
    storageClass: nfs-client
    globalMounts:
    - readOnly: false
      path: /home/app/.local/share/spoolman

