controllers:
  main:
    replicas: 1
    strategy: Recreate
    enabled: true
    containers:
      main:
        env:
          TZ: America/New_York
        probes:
          liveness:
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 10
              failureThreshold: 3
            enabled: true
            type: TCP
            custom: false
          startup:
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 5
              failureThreshold: 30
            enabled: true
            type: TCP
            custom: false
          readiness:
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 10
              failureThreshold: 3
            enabled: true
            type: TCP
            custom: false
        strategy:
          type: Recreate
        resources:
          requests:
            cpu: 5m
        image:
          tag: 0.26.1
          pullPolicy: IfNotPresent
          repository: ghcr.io/donkie/spoolman
    revisionHistoryLimit: 3
    type: deployment
service:
  main:
    primary: true
    ports:
      http:
        primary: true
        port: 8000
        enabled: true
    type: ClusterIP
    controller: main
route:
  main:
    kind: HTTPRoute
    parentRefs:
    - namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
      kind: Gateway
      name: main
    hostnames:
    - spoolman.mattgerega.net
    rules:
    - backendRefs:
      - weight: 1
        kind: Service
        port: 8000
        name: spoolman
        group: ""
      matches:
      - path:
          value: /
          type: PathPrefix
    enabled: true
persistence:
  data:
    storageClass: nfs-client
    size: 2Gi
    accessMode: ReadWriteMany
    globalMounts:
    - readOnly: false
      path: /home/app/.local/share/spoolman
    enabled: true
    type: persistentVolumeClaim

