apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cassandra-secret-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cassandra-secret
    template:
      engineVersion: v2
      data:
          CASSANDRA_PASSWORD: '{{ .password }}'
  data:
  - secretKey: password
    remoteRef:
      key: secrets-k8/monitoring/cassandra
      property: password