dependencies:
- name: prometheus-snmp-exporter
  version: 5.4.0
  repository: https://prometheus-community.github.io/helm-charts
type: application
apiVersion: v2
name: synology-snmp-exporter
version: 5.4.0
description: SNMP Exporter for Synology
appVersion: 1.2.1


