type: application
apiVersion: v2
appVersion: 1.2.1
name: synology-snmp-exporter
description: SNMP Exporter for Synology
version: 9.16.0
dependencies:
- version: 9.16.0
  name: prometheus-snmp-exporter
  repository: https://prometheus-community.github.io/helm-charts


