description: SNMP Exporter for Synology
dependencies:
- repository: https://prometheus-community.github.io/helm-charts
  name: prometheus-snmp-exporter
  version: 8.0.0
appVersion: 1.2.1
apiVersion: v2
type: application
name: synology-snmp-exporter
version: 8.0.0


