dependencies:
- name: prometheus-snmp-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 9.1.0
appVersion: 1.2.1
version: 9.1.0
description: SNMP Exporter for Synology
apiVersion: v2
type: application
name: synology-snmp-exporter


