appVersion: 1.2.1
type: application
apiVersion: v2
dependencies:
  - repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-snmp-exporter
    version: 5.5.0
version: 5.5.0
description: SNMP Exporter for Synology
name: synology-snmp-exporter
