description: SNMP Exporter for Synology
type: application
name: synology-snmp-exporter
dependencies:
- version: 9.13.0
  name: prometheus-snmp-exporter
  repository: https://prometheus-community.github.io/helm-charts
appVersion: 1.2.1
version: 9.13.0
apiVersion: v2


