type: application
version: 9.11.0
apiVersion: v2
dependencies:
- version: 9.11.0
  repository: https://prometheus-community.github.io/helm-charts
  name: prometheus-snmp-exporter
appVersion: 1.2.1
description: SNMP Exporter for Synology
name: synology-snmp-exporter


