name: synology-snmp-exporter
type: application
appVersion: 1.2.1
dependencies:
- version: 2.1.0
  repository: https://prometheus-community.github.io/helm-charts
  name: prometheus-snmp-exporter
description: SNMP Exporter for Synology
version: 2.1.0
apiVersion: v2


