type: application
description: SNMP Exporter for Synology
apiVersion: v2
name: synology-snmp-exporter
dependencies:
- name: prometheus-snmp-exporter
  version: 9.14.1
  repository: https://prometheus-community.github.io/helm-charts
version: 9.14.1
appVersion: 1.2.1


