version: 1.8.2
name: synology-snmp-exporter
appVersion: 1.2.1
dependencies:
- repository: https://prometheus-community.github.io/helm-charts
  version: 1.8.2
  name: prometheus-snmp-exporter
type: application
description: SNMP Exporter for Synology
apiVersion: v2


