description: SNMP Exporter for Synology
apiVersion: v2
appVersion: 1.2.1
type: application
version: 9.0.0
name: synology-snmp-exporter
dependencies:
- version: 9.0.0
  repository: https://prometheus-community.github.io/helm-charts
  name: prometheus-snmp-exporter


