cassandra:
  global:
    storageClass: "nfs-client"
  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: "250Gi"
  dbUser:
    existingSecret:
      name: cassandra-secret
      forcePassword: true
      keyMapping:
        cassandra-password: CASSANDRA_PASSWORD