version: 1.2.1
dependencies:
- version: 1.2.1
  name: prometheus-snmp-exporter
  repository: https://prometheus-community.github.io/helm-charts
name: prometheus-snmp-exporter
apiVersion: v2
description: SNMP Exporter
appVersion: "1.2.1"
type: application


