prometheus-snmp-exporter:
  ingress: 
    enabled: true
    hosts:
      - hosts: snmpexporter.mattgerega.net
        paths:
        - path: /
          pathType: Prefix
    annotations: 
      kubernetes.io/ingress.class: nginx