apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ilo-pxhp-credentials-es
  namespace: cluster-tools

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ilo-pxhp-credentials
  data:
    - secretKey: ILO_USER
      remoteRef:
        key: secrets-k8/infra/ilo-pxhp
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ILO_PASS
      remoteRef:
        key: secrets-k8/infra/ilo-pxhp
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
