apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ilo-log-poller-state
  namespace: cluster-tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 64Mi
