apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: mimir-minio-secret-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mimir-minio-secret
  data:
  - secretKey: MINIO_USERNAME
    remoteRef:
      key: secrets-k8/monitoring/minio
      property: username
  - secretKey: MINIO_PASSWORD
    remoteRef:
      key: secrets-k8/monitoring/minio
      property: password