controllers:
  main:
    revisionHistoryLimit: 3
    strategy: Recreate
    type: deployment
    containers:
      main:
        image:
          repository: ghcr.io/unpoller/unpoller
          pullPolicy: IfNotPresent
          tag: v5.2.6
        env:
          UP_UNIFI_DEFAULT_URL: https://unifi
          TZ: America/New_York
          UP_INFLUXDB_DISABLE: true
        probes:
          startup:
            type: TCP
            custom: false
            spec:
              periodSeconds: 5
              initialDelaySeconds: 0
              failureThreshold: 30
              timeoutSeconds: 1
            enabled: true
          readiness:
            type: TCP
            custom: false
            spec:
              periodSeconds: 10
              initialDelaySeconds: 0
              failureThreshold: 3
              timeoutSeconds: 1
            enabled: true
          liveness:
            type: TCP
            custom: false
            spec:
              periodSeconds: 10
              initialDelaySeconds: 0
              failureThreshold: 3
              timeoutSeconds: 1
            enabled: true
        envFrom:
        - secretRef:
            name: unifi-poller
        resources:
          requests:
            cpu: 10m
    enabled: true
    replicas: 1
service:
  main:
    annotations:
      metrics.spydersoft.io/scrape: "true"
      metrics.spydersoft.io/port: "9130"
      metrics.spydersoft.io/scheme: http
      metrics.spydersoft.io/path: /metrics
    type: ClusterIP
    ports:
      metrics:
        protocol: TCP
        primary: true
        port: 9130
        enabled: true
      http:
        enabled: false
    primary: true
    controller: main
serviceMonitor:
  main:
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
    - interval: 1m
      port: metrics
      scrapeTimeout: 30s
      path: /metrics
      scheme: http
    enabled: false
influxdb:
  architecture: standalone
  persistence:
    enabled: false
  database: unifi
  enabled: false
  authEnabled: false
ingress:
  main:
    enabled: false

