serviceMonitor:
  main:
    endpoints:
    - path: /metrics
      scrapeTimeout: 30s
      interval: 1m
      scheme: http
      port: metrics
    enabled: false
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
controllers:
  main:
    strategy: Recreate
    enabled: true
    revisionHistoryLimit: 3
    containers:
      main:
        image:
          tag: v5.1.0
          repository: ghcr.io/unpoller/unpoller
          pullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: unifi-poller
        probes:
          readiness:
            type: TCP
            enabled: true
            custom: false
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              failureThreshold: 3
              timeoutSeconds: 1
          startup:
            type: TCP
            enabled: true
            custom: false
            spec:
              initialDelaySeconds: 0
              periodSeconds: 5
              failureThreshold: 30
              timeoutSeconds: 1
          liveness:
            type: TCP
            enabled: true
            custom: false
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              failureThreshold: 3
              timeoutSeconds: 1
        env:
          UP_UNIFI_DEFAULT_URL: https://unifi
          UP_INFLUXDB_DISABLE: true
          TZ: America/New_York
        resources:
          requests:
            cpu: 10m
    type: deployment
    replicas: 1
service:
  main:
    ports:
      http:
        enabled: false
      metrics:
        enabled: true
        port: 9130
        protocol: TCP
        primary: true
    annotations:
      metrics.spydersoft.io/port: "9130"
      metrics.spydersoft.io/path: /metrics
      metrics.spydersoft.io/scheme: http
      metrics.spydersoft.io/scrape: "true"
    primary: true
    controller: main
    type: ClusterIP
ingress:
  main:
    enabled: false
influxdb:
  enabled: false
  architecture: standalone
  persistence:
    enabled: false
  authEnabled: false
  database: unifi

