ingress:
  main:
    enabled: false
serviceMonitor:
  main:
    enabled: false
    serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
    endpoints:
    - scheme: http
      path: /metrics
      scrapeTimeout: 30s
      port: metrics
      interval: 1m
controllers:
  main:
    revisionHistoryLimit: 3
    replicas: 1
    type: deployment
    enabled: true
    strategy: Recreate
    containers:
      main:
        envFrom:
        - secretRef:
            name: unifi-poller
        image:
          tag: v3.3.4
          repository: ghcr.io/unpoller/unpoller
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 10m
        env:
          TZ: America/New_York
          UP_INFLUXDB_DISABLE: true
          UP_UNIFI_DEFAULT_URL: https://unifi
        probes:
          liveness:
            enabled: true
            custom: false
            type: TCP
            spec:
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              initialDelaySeconds: 0
          readiness:
            enabled: true
            custom: false
            type: TCP
            spec:
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              initialDelaySeconds: 0
          startup:
            enabled: true
            custom: false
            type: TCP
            spec:
              periodSeconds: 5
              timeoutSeconds: 1
              failureThreshold: 30
              initialDelaySeconds: 0
influxdb:
  architecture: standalone
  database: unifi
  persistence:
    enabled: false
  enabled: false
  authEnabled: false
service:
  main:
    controller: main
    type: ClusterIP
    annotations:
      metrics.spydersoft.io/scrape: "true"
      metrics.spydersoft.io/path: /metrics
      metrics.spydersoft.io/scheme: http
      metrics.spydersoft.io/port: "9130"
    ports:
      http:
        enabled: false
      metrics:
        enabled: true
        port: 9130
        primary: true
        protocol: TCP
    primary: true

