dependencies:
- version: 10.5.15
  name: grafana
  repository: https://grafana.github.io/helm-charts
- version: 4.6.2
  name: common
  repository: https://bjw-s-labs.github.io/helm-charts
apiVersion: v2
type: application
name: grafana
version: 10.5.15


