name: grafana
version: 5.1.0
type: application
dependencies:
- repository: https://grafana.github.io/helm-charts
  name: grafana
  version: 10.5.15
- repository: "oci://ghcr.io/bjw-s-labs/helm"
  name: common
  version: 5.2.0
apiVersion: v2
