service:
  postgres:
    type: ClusterIP
    controller: postgres
    primary: false
    ports:
      postgres:
        enabled: true
        port: 5432
  main:
    enabled: false
global:
  nameOverride: postgres
grafanaBackup:
  image:
    tag: v1.5.0
    repository: dealfa/grafana-backup-tool
  schedule: 0 4 * * *
  enabled: true
persistence:
  postgres-secrets:
    type: secret
    name: postgres-secrets
    enabled: true
  postgres-data:
    type: persistentVolumeClaim
    storageClass: nfs-client
    size: 300Gi
    advancedMounts:
      postgres:
        main:
        - path: /var/lib/postgresql/data
    enabled: true
    accessMode: ReadWriteMany
  postgres-init-data:
    type: configMap
    advancedMounts:
      postgres:
        main:
        - path: /docker-entrypoint-initdb.d/init-grafana-user.sh
          subPath: init-data.sh
    identifier: postgres-init-data
    enabled: true
grafana:
  service:
    annotations:
      linkerd.io/inject: enabled
  plugins:
  - grafana-piechart-panel
  admin:
    passwordKey: GRAFANA_ADMIN_PASSWORD
    existingSecret: grafana-admin-secret
    userKey: GRAFANA_ADMIN_USER
  ingress:
    pathType: Prefix
    tls: []
    path: /
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
    - grafana.mattgerega.net
  serviceMonitor:
    enabled: false
  podAnnotations:
    linkerd.io/inject: enabled
  envFromSecret: grafana-auth-secret
  revisionHistoryLimit: 1
  persistence:
    storageClassName: nfs-client
    enabled: true
  grafana.ini:
    server:
      domain: grafana.mattgerega.net
      root_url: https://grafana.mattgerega.net
    database:
      type: postgres
      host: grafana-postgres
      name: grafana
    azure:
      managed_identity_enabled: true
    auth.azuread:
      allow_sign_up: true
      token_url: https://login.microsoftonline.com/70965cdd-c60c-4109-9fcf-709b2f23bd0c/oauth2/v2.0/token
      enabled: true
      auth_url: https://login.microsoftonline.com/70965cdd-c60c-4109-9fcf-709b2f23bd0c/oauth2/v2.0/authorize
      role_attribute_strict: false
      name: Azure AD
      scopes: openid email profile
controllers:
  postgres:
    type: deployment
    containers:
      main:
        image:
          pullPolicy: IfNotPresent
          tag: 17
          repository: postgres
        strategy:
          type: Recreate
        env:
        - name: POSTGRES_PORT
          value: 5432
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_DB
          value: grafana
        envFrom:
        - secretRef:
            name: postgres-secrets
    strategy: Recreate
    enabled: true
    revisionHistoryLimit: 3
    replicas: 1
  main:
    enabled: false
configMaps:
  postgres-init-data:
    data:
      init-data.sh: |
        #!/bin/bash
        set -e;
        if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
          psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE USER "${POSTGRES_NON_ROOT_USER}" WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
            GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO "${POSTGRES_NON_ROOT_USER}";
            ALTER DATABASE ${POSTGRES_DB} OWNER TO "${POSTGRES_NON_ROOT_USER}";
        EOSQL
        else
          echo "SETUP INFO: No Environment variables given!"
        fi
    enabled: true

